openapi: '3.0.0'
info:
  title: API Title
  version: '1.0'
paths:
  /reset-password:
    post:
      tags:
        - Password
      summary: 비밀번호 찾기 API입니다.
      description: 비밀번호 찾기 API입니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            example:
              email: "fffgpfal@naver.com"
      responses:
        '200':
          description: Successful response
        '404':
          description: 사용자를 찾을 수 없습니다.
        '500':
          description: 서버 오류

components:
  schemas:
    user:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string

